### ISSUE TITLE
*Faster* Withdrawals via (Async RageQuit).as_collateral()

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine#1]
Make the `RageQuit` an `async fn` such that it returns a `future`, a proxy to the eventual response, which in this context represents a promise that funds will be unlocked. This `future` could be used as collateral for a loan from a MakerDAO-esque parachain. 

**Purpose**: near instant withdrawals vs the current paradigm which requires an exiting member to poll the proposal queue until all supported proposals have been passed (as well as exited the grace period meant for dissenters).

## Why?

Let's say that `Voter_1` votes `no` on Proposal `A` and then `yes` on Proposal `B` (assume `A` is proposed and voted on *before* `B`). `Voter_1` cannot exit even if `A` passes because they already voted `yes` on B. This redefines the "instant withdrawal" that MolochDAO claims to achieve. 

Lock-in is important, but so is instant withdrawals. They're at odds with each other, but using the request to withdraw as a collateral for a loan is a workaround that enables the leaving member to achieve a *faster* exit.

**Comment by AmarRSingh** [comment]
The main thing is the `RageQuit` function. I think this should be re-implemented such that it returns a `future`, a proxy to the eventual response (which would probably be the unlocking of funds). This `future` could then be used as collateral for a loan from nczhu's project (or any MakerDAO-esque parachain).

**Comment by 4meta5** [comment]
This is unnecessarily complex.
