### ISSUE TITLE
MetaGovernance

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine#11]
The  **value proposition** of Sunshine comes from the modularity that it derives from Substrate (*and* Substrate gets from Rust); Sunshine is designed to eventually be easily forkable into different organizations with different structures. Additionally, it is designed to empower the system's actors to dynamically update their signalling mechanisms as well as any other significant configurations. 

Rather than preferring rigid stability, Sunshine encourages fluidity. The idea is to realize forkless upgrades for organizations by leveraging the specific properties that make Polkadot a resilient, yet flexible meta-protocol. The main reason for this is that the runtime is encoded in Rust, compiled down to WASM, and stored on-chain. By encoding the rules for updating the WASM stored on-chain in the runtime logic, Substrate is the perfect playground for high performance meta-protocols.

The truth is that everything requires upgrades. In software development, progress moves at a rapid pace and it is extremely useful to be able to make expressive changes to the organization's structure and rules. 

**Specific Pros** <br>
* enable coordinated response to attacks
* encourage incorporation of modern research into running protocols.
* empower other teams to experiment with different organizational structures in different use case areas -- *experimentation in parallel is more productive than sequential trials*

This whole project is an experiment, but it strives to answer the question of "how far can Substrate's modularity really take us with respect to building flexible meta-protocols at the application layer?"

**Comment by AmarRSingh** [comment]
# Code

Define a metagovernance trait. Still playing with structure...
