### ISSUE TITLE
Key Management

### ISSUE THREAD

**Issue by 4meta5** [web3garden/sunshine#2]
[MolochDAO](https://github.com/MolochVentures/moloch) allows key delegation in which members can have multiple `AccountId`s associated with their membership. This is encoded as map from `address => address` [here](https://github.com/MolochVentures/moloch/blob/master/flatten/Moloch.sol#L80). 

It should be pretty easy to add this functionality to MoloChameleon. An example of similar logic in a different context can be found in the [`sudo`](https://github.com/paritytech/substrate/blob/master/srml/sudo/src/lib.rs) module as the `set_key` function.

**Comment by AmarRSingh** [comment]
**Action Delegation** -- signing to allow transfers on behalf of a set of keys is also interesting. When implemented with modules, this seems like a use case for PRE, but it might be overkill. The contracts-style development does it something like [this](https://shawntabrizi.github.io/substrate-contracts-workshop/#/2/supporting-approvals-and-transfer-from).

**Comment by 4meta5** [comment]
scattered and not focused...

would just get solved with an `Id => Vec<AccountId>` map in storage also
